### ISSUE TITLE
Memory issue when model can not load.

### ISSUE THREAD

**Issue by MarketingPip** [TranscribeJs/transcribe.js#10]
The library uses excessive memory when the model is NOT found in path provided.

As well blobs should be provided etc. Tho could be turned into base64 url?

**Comment by thurti** [comment]
> The library uses excessive memory when the model is NOT found in path provided.

I will check the init method. I guess the error handling needs some improvement.

> As well blobs should be provided etc. Tho could be turned into base64 url?  

Can you please explain this in more detail? *Where* should a blob *of what* be provided?

Regarding the model file, the `model` option can be of type ` File | string` . You can use the [File API](https://developer.mozilla.org/en-US/docs/Web/API/File) to create a new File object from a blob or a base64 encoded string.

**Comment by MarketingPip** [comment]
@thurti I was thinking passing blob for transcribing - tho that might be stupid (since we can just turn blob into base64 string right? (so maybe just skip that?)

```js
// transcribe audio/video file
const result = await transcriber.transcribe(BLOB here);

console.log(result);
```

but as for fetching / memory issue when model is not found via fetch etc.. Definitely needs a fix. For some reason I think the model is still trying to be init with nothing in it. (tho I have not looked in the code to confirm this)

**Comment by thurti** [comment]
> I was thinking passing blob for transcribing

You can use the File API to create a file object from a blob
```js
// transcribe audio/video file
const result = await transcriber.transcribe( new File([BLOB here], "myBlob.wav") );
```

> but as for fetching / memory issue when model is not found via fetch etc.. Definitely needs a fix. 

#11 will fix this in the next release.
