### ISSUE TITLE
Getting Transcribe to build inside SvelteKit app

### ISSUE THREAD

**Issue by henryhugginsx** [TranscribeJs/transcribe.js#4]
[Here is a minimal app that reproduces the issue: ](https://stackblitz.com/edit/sveltejs-kit-template-default-fhxpyw?description=The%20default%20SvelteKit%20template,%20generated%20with%20create-svelte&file=package.json,src%2Froutes%2F%2Bpage.svelte&title=SvelteKit%20Default%20Template)

Just Ctrl+C the app, and run "npm run build" instead.

```
❯ npm run build

> kit-template-default@0.0.1 build
> vite build

vite v5.4.11 building SSR bundle for production...
"default" is imported from external module "@transcribe/shout" but never used in "src/routes/+page.svelte".
✓ 163 modules transformed.
vite v5.4.11 building for production...
[plugin:vite:resolve] [plugin vite:resolve] Module "module" has been externalized for browser compatibility, imported by "/home/projects/sveltejs-kit-template-default-fhxpyw/node_modules/@transcribe/shout/src/shout/shout.wasm.worker.mjs". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "module" has been externalized for browser compatibility, imported by "/home/projects/sveltejs-kit-template-default-fhxpyw/node_modules/@transcribe/shout/src/shout/shout.wasm.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
node_modules/@transcribe/shout/src/shout/shout.wasm.js (8:1242593): Use of eval in "node_modules/@transcribe/shout/src/shout/shout.wasm.js" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 137 modules transformed.
x Build failed in 837ms
x Build failed in 4.72s
error during build:
[vite-plugin-sveltekit-compile] [commonjs--resolver] Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
file: /home/projects/sveltejs-kit-template-default-fhxpyw/node_modules/@transcribe/shout/src/shout/shout.wasm.js
file: /home/projects/sveltejs-kit-template-default-fhxpyw/node_modules/@transcribe/shout/src/shout/shout.wasm.js
[commonjs--resolver] Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
file: /home/projects/sveltejs-kit-template-default-fhxpyw/node_modules/@transcribe/shout/src/shout/shout.wasm.js
    at getRollupError (file:///home/projects/sveltejs-kit-template-default-fhxpyw/node_modules/rollup/dist/es/shared/parseAst.js:558:41)
    at error (file:///home/projects/sveltejs-kit-template-default-fhxpyw/node_modules/rollup/dist/es/shared/parseAst.js:554:42)
    at validateOptionsForMultiChunkOutput (file:///home/projects/sveltejs-kit-template-default-fhxpyw/node_modules/rollup/dist/es/shared/node-entry.js:19602:29)
    at generate (file:///home/projects/sveltejs-kit-template-default-fhxpyw/node_modules/rollup/dist/es/shared/node-entry.js:19494:51)
```

All I did beyond forking the "hello word sveltkit app": in src/routes/+page.svelte, I added the line `import createModule from "@transcribe/shout";`

Is there a way to recompile the `shout.wasm.js` and `shout.wasm.worker.mjs` files to have compatible modules?

**Comment by MarketingPip** [comment]
@henryhugginsx - modify the code to USE the build. Currently the link / app you posted does not use File Transcriber at all. Which your error messages explicitly states `imported from external module "@transcribe/shout" but never used in "src/routes/+page.svelte".` 

So call the module like the example given in README.

```js
import createModule from "/your/project/shout.wasm.js"; // path where you've copied before
// import createModule from "@transcribe/shout";  // if you use an import map
import { FileTranscriber } from "@transcribe/transcriber";

// create new instance
const transcriber = new FileTranscriber({
  createModule, // create module function from emscripten build
  model: "/your/project/ggml-tiny-q5_1.bin", // path to ggml model file
  workerPath: "/your/project", // directory of shout.wasm.worker.mjs copied before
});

// init wasm transcriber worker
await transcriber.init();

// transcribe audio/video file
const result = await transcriber.transcribe("/your/project/my.mp3");

console.log(result);
``` 


But - as far it looks this is a issue with your code / error being thrown in the build process. Not anything to do with this library.

**Comment by henryhugginsx** [comment]
@MarketingPip I just wanted to reproduce the compiler issue with minimal distractions.

[Here is an example of trying to render the createModule function in the template](https://stackblitz.com/edit/sveltejs-kit-template-default-3mhqhb?description=The%20default%20SvelteKit%20template,%20generated%20with%20create-svelte&file=package.json,src%2Froutes%2F%2Bpage.svelte&title=SvelteKit%20Default%20Template), so it is clear that the module is being imported. 

The problem is with the `vite build` step, where the compiler tries to minify this library.

There isn't much point in importing `FileTranscriber ` and other setup, when the `import createModule` part is not compiling.

In the original stackblitz, if you comment out the `import createModule from "@transcribe/shout";`, everything compiles nicely.

**Comment by MarketingPip** [comment]
@henryhugginsx try this in a non stackblitz environment and change the output for `output.format`. Again tho - this is not an issue for Transcribe.js. Tho maybe @thurti can add some insight - if I am wrong...

**Comment by thurti** [comment]
My first guess was to exclude the package from the SvelteKit rollup build. But then the import doesn't work anymore (obviously).

```js
//vite.config.ts
...
build: {
    rollupOptions: {
      external: ["@transcribe/shout"],
    },
},
```
I'll have a look. I'm still not sure what's the best way to handle the import/use of the wasm files. Ideas are very welcome.

Also the exports from `@transcribe/transcriber` don't work in SvelteKit (#6). But that's quickly fixed.

**Comment by thurti** [comment]
@henryhugginsx 

The only solution I've found is to exclude the file  from the bundler and use a dynamic `import(/shout.wasm.js?url)`. 

```js
//vite.config.ts
...
build: {
    rollupOptions: {
      external: ["/shout.wasm.js?url"],
    },
},
```

```js
// +page.svelte
import { onMount } from "svelte";
import { FileTranscriber } from "@transcribe/transcriber";

let createModule;

// ... use transcriber

onMount(async () => {
  // dynamic import wasm module from /static
  // this is a workaround because Rollup can't bundle this file
  createModule = (await import("/shout.wasm.js?url")).default;
});
```

I've made an [example repo](https://github.com/TranscribeJs/examples/tree/main/svelte-kit) on how to get this to work in SvelteKit. I've also added an [integration guide](https://www.transcribejs.dev/docs/svelte-kit/) in the docs.

**Comment by thurti** [comment]
A bit more insights:
> Is there a way to recompile the shout.wasm.js and shout.wasm.worker.mjs files to have compatible modules?
The module is compiled with emscrtipten EXPORT_ES6 option enabled. So it's already a valid ES6 module. Unfortunately, rollup seems to disagree.

Feel free to re-open the issue if there are problems with the provided solution.
